### ISSUE TITLE
没有后台网页部分的源代码

### ISSUE THREAD

**Issue by ryysoft** [wangluoxiaozhazha/online-education#1]
谢谢回复。

**Comment by wangluoxiaozhazha** [comment]
有的呀

**Comment by wangluoxiaozhazha** [comment]
online-education(服务端)在这个模块里的web模块里的template里，用的是thymelef模板引擎

**Comment by wangluoxiaozhazha** [comment]
online-education(服务端)在这个模块里的web模块里的template里，用的是thymelef模板引擎

**Comment by ZuoSou** [comment]
请问一下客户端的图片是在哪里加载出来的，为啥安卓模拟器运行出来没有主界面的图片

**Comment by wangluoxiaozhazha** [comment]
你指的是什么图片，上传课程的图片？还是刚进去封面广告的图片

**Comment by ZuoSou** [comment]
> 你指的是什么图片，上传课程的图片？还是刚进去封面广告的图片

就是上传课程的图片，只有文字，文字上面是空白的界面

**Comment by ZuoSou** [comment]
> 你指的是什么图片，上传课程的图片？还是刚进去封面广告的图片

现在解决了，麻烦了

**Comment by 1941302069** [comment]
请问一下agp 和gradle版本还有jdk都是什么版本呀

**Comment by 1941302069** [comment]
> > 你指的是什么图片，上传课程的图片？还是刚进去封面广告的图片
> 
> 现在解决了，麻烦了

你好请问怎么解决的呀求告知

**Comment by wangluoxiaozhazha** [comment]
已解决
